# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-26 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='gallery/')),
                ('image_link', models.TextField(blank=True)),
                ('image_name', models.TextField(blank=True, max_length=60)),
                ('details', models.TextField(blank=60, max_length=60)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(blank=True, to='pgallery.Category')),
            ],
        ),
    ]
